[tool.poetry]
name = "mlmirna"
version = "0.1.0"
description = "ML-based feature selection for transcriptomic data"
authors = ["German <german.osmak@gmail.com>"]
license = "Apache license 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.3.5"
sklearn = "^0.0.post9"
scipy = "^1.7.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
